// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_protocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_protocol_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protocol_2eproto;
namespace NJoy {
class Axis;
class AxisDefaultTypeInternal;
extern AxisDefaultTypeInternal _Axis_default_instance_;
class Button;
class ButtonDefaultTypeInternal;
extern ButtonDefaultTypeInternal _Button_default_instance_;
class Hat;
class HatDefaultTypeInternal;
extern HatDefaultTypeInternal _Hat_default_instance_;
class JoyData;
class JoyDataDefaultTypeInternal;
extern JoyDataDefaultTypeInternal _JoyData_default_instance_;
class JoyListData;
class JoyListDataDefaultTypeInternal;
extern JoyListDataDefaultTypeInternal _JoyListData_default_instance_;
class Ping;
class PingDefaultTypeInternal;
extern PingDefaultTypeInternal _Ping_default_instance_;
}  // namespace NJoy
PROTOBUF_NAMESPACE_OPEN
template<> ::NJoy::Axis* Arena::CreateMaybeMessage<::NJoy::Axis>(Arena*);
template<> ::NJoy::Button* Arena::CreateMaybeMessage<::NJoy::Button>(Arena*);
template<> ::NJoy::Hat* Arena::CreateMaybeMessage<::NJoy::Hat>(Arena*);
template<> ::NJoy::JoyData* Arena::CreateMaybeMessage<::NJoy::JoyData>(Arena*);
template<> ::NJoy::JoyListData* Arena::CreateMaybeMessage<::NJoy::JoyListData>(Arena*);
template<> ::NJoy::Ping* Arena::CreateMaybeMessage<::NJoy::Ping>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace NJoy {

enum UpdateType : int {
  PING = 1,
  AXIS = 2,
  BUTTON = 3,
  HAT = 4
};
bool UpdateType_IsValid(int value);
constexpr UpdateType UpdateType_MIN = PING;
constexpr UpdateType UpdateType_MAX = HAT;
constexpr int UpdateType_ARRAYSIZE = UpdateType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* UpdateType_descriptor();
template<typename T>
inline const std::string& UpdateType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, UpdateType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function UpdateType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    UpdateType_descriptor(), enum_t_value);
}
inline bool UpdateType_Parse(
    const std::string& name, UpdateType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<UpdateType>(
    UpdateType_descriptor(), name, value);
}
// ===================================================================

class Ping :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NJoy.Ping) */ {
 public:
  Ping();
  virtual ~Ping();

  Ping(const Ping& from);
  Ping(Ping&& from) noexcept
    : Ping() {
    *this = ::std::move(from);
  }

  inline Ping& operator=(const Ping& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ping& operator=(Ping&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Ping& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ping* internal_default_instance() {
    return reinterpret_cast<const Ping*>(
               &_Ping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Ping& a, Ping& b) {
    a.Swap(&b);
  }
  inline void Swap(Ping* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Ping* New() const final {
    return CreateMaybeMessage<Ping>(nullptr);
  }

  Ping* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Ping>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Ping& from);
  void MergeFrom(const Ping& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ping* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NJoy.Ping";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTokenFieldNumber = 1,
  };
  // required int32 token = 1;
  bool has_token() const;
  void clear_token();
  ::PROTOBUF_NAMESPACE_ID::int32 token() const;
  void set_token(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:NJoy.Ping)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 token_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class Axis :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NJoy.Axis) */ {
 public:
  Axis();
  virtual ~Axis();

  Axis(const Axis& from);
  Axis(Axis&& from) noexcept
    : Axis() {
    *this = ::std::move(from);
  }

  inline Axis& operator=(const Axis& from) {
    CopyFrom(from);
    return *this;
  }
  inline Axis& operator=(Axis&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Axis& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Axis* internal_default_instance() {
    return reinterpret_cast<const Axis*>(
               &_Axis_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Axis& a, Axis& b) {
    a.Swap(&b);
  }
  inline void Swap(Axis* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Axis* New() const final {
    return CreateMaybeMessage<Axis>(nullptr);
  }

  Axis* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Axis>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Axis& from);
  void MergeFrom(const Axis& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Axis* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NJoy.Axis";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // required int32 index = 1;
  bool has_index() const;
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);

  // required int32 value = 2;
  bool has_value() const;
  void clear_value();
  ::PROTOBUF_NAMESPACE_ID::int32 value() const;
  void set_value(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:NJoy.Axis)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  ::PROTOBUF_NAMESPACE_ID::int32 value_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class Button :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NJoy.Button) */ {
 public:
  Button();
  virtual ~Button();

  Button(const Button& from);
  Button(Button&& from) noexcept
    : Button() {
    *this = ::std::move(from);
  }

  inline Button& operator=(const Button& from) {
    CopyFrom(from);
    return *this;
  }
  inline Button& operator=(Button&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Button& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Button* internal_default_instance() {
    return reinterpret_cast<const Button*>(
               &_Button_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Button& a, Button& b) {
    a.Swap(&b);
  }
  inline void Swap(Button* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Button* New() const final {
    return CreateMaybeMessage<Button>(nullptr);
  }

  Button* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Button>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Button& from);
  void MergeFrom(const Button& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Button* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NJoy.Button";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // required int32 index = 1;
  bool has_index() const;
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);

  // required bool value = 2;
  bool has_value() const;
  void clear_value();
  bool value() const;
  void set_value(bool value);

  // @@protoc_insertion_point(class_scope:NJoy.Button)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  bool value_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class Hat :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NJoy.Hat) */ {
 public:
  Hat();
  virtual ~Hat();

  Hat(const Hat& from);
  Hat(Hat&& from) noexcept
    : Hat() {
    *this = ::std::move(from);
  }

  inline Hat& operator=(const Hat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Hat& operator=(Hat&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Hat& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Hat* internal_default_instance() {
    return reinterpret_cast<const Hat*>(
               &_Hat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Hat& a, Hat& b) {
    a.Swap(&b);
  }
  inline void Swap(Hat* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Hat* New() const final {
    return CreateMaybeMessage<Hat>(nullptr);
  }

  Hat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Hat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Hat& from);
  void MergeFrom(const Hat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Hat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NJoy.Hat";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexFieldNumber = 1,
    kValueFieldNumber = 2,
  };
  // required int32 index = 1;
  bool has_index() const;
  void clear_index();
  ::PROTOBUF_NAMESPACE_ID::int32 index() const;
  void set_index(::PROTOBUF_NAMESPACE_ID::int32 value);

  // required int32 value = 2;
  bool has_value() const;
  void clear_value();
  ::PROTOBUF_NAMESPACE_ID::int32 value() const;
  void set_value(::PROTOBUF_NAMESPACE_ID::int32 value);

  // @@protoc_insertion_point(class_scope:NJoy.Hat)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 index_;
  ::PROTOBUF_NAMESPACE_ID::int32 value_;
  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class JoyData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NJoy.JoyData) */ {
 public:
  JoyData();
  virtual ~JoyData();

  JoyData(const JoyData& from);
  JoyData(JoyData&& from) noexcept
    : JoyData() {
    *this = ::std::move(from);
  }

  inline JoyData& operator=(const JoyData& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoyData& operator=(JoyData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JoyData& default_instance();

  enum TestOneofCase {
    kPing = 2,
    kAxis = 3,
    kButton = 4,
    kHat = 5,
    TEST_ONEOF_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JoyData* internal_default_instance() {
    return reinterpret_cast<const JoyData*>(
               &_JoyData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(JoyData& a, JoyData& b) {
    a.Swap(&b);
  }
  inline void Swap(JoyData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JoyData* New() const final {
    return CreateMaybeMessage<JoyData>(nullptr);
  }

  JoyData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JoyData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JoyData& from);
  void MergeFrom(const JoyData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JoyData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NJoy.JoyData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTypeFieldNumber = 1,
    kPingFieldNumber = 2,
    kAxisFieldNumber = 3,
    kButtonFieldNumber = 4,
    kHatFieldNumber = 5,
  };
  // required .NJoy.UpdateType type = 1;
  bool has_type() const;
  void clear_type();
  ::NJoy::UpdateType type() const;
  void set_type(::NJoy::UpdateType value);

  // optional .NJoy.Ping ping = 2;
  bool has_ping() const;
  void clear_ping();
  const ::NJoy::Ping& ping() const;
  ::NJoy::Ping* release_ping();
  ::NJoy::Ping* mutable_ping();
  void set_allocated_ping(::NJoy::Ping* ping);

  // optional .NJoy.Axis axis = 3;
  bool has_axis() const;
  void clear_axis();
  const ::NJoy::Axis& axis() const;
  ::NJoy::Axis* release_axis();
  ::NJoy::Axis* mutable_axis();
  void set_allocated_axis(::NJoy::Axis* axis);

  // optional .NJoy.Button button = 4;
  bool has_button() const;
  void clear_button();
  const ::NJoy::Button& button() const;
  ::NJoy::Button* release_button();
  ::NJoy::Button* mutable_button();
  void set_allocated_button(::NJoy::Button* button);

  // optional .NJoy.Hat hat = 5;
  bool has_hat() const;
  void clear_hat();
  const ::NJoy::Hat& hat() const;
  ::NJoy::Hat* release_hat();
  ::NJoy::Hat* mutable_hat();
  void set_allocated_hat(::NJoy::Hat* hat);

  void clear_test_oneof();
  TestOneofCase test_oneof_case() const;
  // @@protoc_insertion_point(class_scope:NJoy.JoyData)
 private:
  class _Internal;
  void set_has_ping();
  void set_has_axis();
  void set_has_button();
  void set_has_hat();

  inline bool has_test_oneof() const;
  inline void clear_has_test_oneof();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int type_;
  union TestOneofUnion {
    TestOneofUnion() {}
    ::NJoy::Ping* ping_;
    ::NJoy::Axis* axis_;
    ::NJoy::Button* button_;
    ::NJoy::Hat* hat_;
  } test_oneof_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_protocol_2eproto;
};
// -------------------------------------------------------------------

class JoyListData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NJoy.JoyListData) */ {
 public:
  JoyListData();
  virtual ~JoyListData();

  JoyListData(const JoyListData& from);
  JoyListData(JoyListData&& from) noexcept
    : JoyListData() {
    *this = ::std::move(from);
  }

  inline JoyListData& operator=(const JoyListData& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoyListData& operator=(JoyListData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const JoyListData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JoyListData* internal_default_instance() {
    return reinterpret_cast<const JoyListData*>(
               &_JoyListData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(JoyListData& a, JoyListData& b) {
    a.Swap(&b);
  }
  inline void Swap(JoyListData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline JoyListData* New() const final {
    return CreateMaybeMessage<JoyListData>(nullptr);
  }

  JoyListData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<JoyListData>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const JoyListData& from);
  void MergeFrom(const JoyListData& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JoyListData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NJoy.JoyListData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_protocol_2eproto);
    return ::descriptor_table_protocol_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // repeated .NJoy.JoyData data = 1;
  int data_size() const;
  void clear_data();
  ::NJoy::JoyData* mutable_data(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::NJoy::JoyData >*
      mutable_data();
  const ::NJoy::JoyData& data(int index) const;
  ::NJoy::JoyData* add_data();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::NJoy::JoyData >&
      data() const;

  // @@protoc_insertion_point(class_scope:NJoy.JoyListData)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::NJoy::JoyData > data_;
  friend struct ::TableStruct_protocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Ping

// required int32 token = 1;
inline bool Ping::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Ping::clear_token() {
  token_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Ping::token() const {
  // @@protoc_insertion_point(field_get:NJoy.Ping.token)
  return token_;
}
inline void Ping::set_token(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  token_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Ping.token)
}

// -------------------------------------------------------------------

// Axis

// required int32 index = 1;
inline bool Axis::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Axis::clear_index() {
  index_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Axis::index() const {
  // @@protoc_insertion_point(field_get:NJoy.Axis.index)
  return index_;
}
inline void Axis::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  index_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Axis.index)
}

// required int32 value = 2;
inline bool Axis::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Axis::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Axis::value() const {
  // @@protoc_insertion_point(field_get:NJoy.Axis.value)
  return value_;
}
inline void Axis::set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  value_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Axis.value)
}

// -------------------------------------------------------------------

// Button

// required int32 index = 1;
inline bool Button::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Button::clear_index() {
  index_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Button::index() const {
  // @@protoc_insertion_point(field_get:NJoy.Button.index)
  return index_;
}
inline void Button::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  index_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Button.index)
}

// required bool value = 2;
inline bool Button::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Button::clear_value() {
  value_ = false;
  _has_bits_[0] &= ~0x00000002u;
}
inline bool Button::value() const {
  // @@protoc_insertion_point(field_get:NJoy.Button.value)
  return value_;
}
inline void Button::set_value(bool value) {
  _has_bits_[0] |= 0x00000002u;
  value_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Button.value)
}

// -------------------------------------------------------------------

// Hat

// required int32 index = 1;
inline bool Hat::has_index() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Hat::clear_index() {
  index_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Hat::index() const {
  // @@protoc_insertion_point(field_get:NJoy.Hat.index)
  return index_;
}
inline void Hat::set_index(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  index_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Hat.index)
}

// required int32 value = 2;
inline bool Hat::has_value() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Hat::clear_value() {
  value_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Hat::value() const {
  // @@protoc_insertion_point(field_get:NJoy.Hat.value)
  return value_;
}
inline void Hat::set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  value_ = value;
  // @@protoc_insertion_point(field_set:NJoy.Hat.value)
}

// -------------------------------------------------------------------

// JoyData

// required .NJoy.UpdateType type = 1;
inline bool JoyData::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JoyData::clear_type() {
  type_ = 1;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::NJoy::UpdateType JoyData::type() const {
  // @@protoc_insertion_point(field_get:NJoy.JoyData.type)
  return static_cast< ::NJoy::UpdateType >(type_);
}
inline void JoyData::set_type(::NJoy::UpdateType value) {
  assert(::NJoy::UpdateType_IsValid(value));
  _has_bits_[0] |= 0x00000001u;
  type_ = value;
  // @@protoc_insertion_point(field_set:NJoy.JoyData.type)
}

// optional .NJoy.Ping ping = 2;
inline bool JoyData::has_ping() const {
  return test_oneof_case() == kPing;
}
inline void JoyData::set_has_ping() {
  _oneof_case_[0] = kPing;
}
inline void JoyData::clear_ping() {
  if (has_ping()) {
    delete test_oneof_.ping_;
    clear_has_test_oneof();
  }
}
inline ::NJoy::Ping* JoyData::release_ping() {
  // @@protoc_insertion_point(field_release:NJoy.JoyData.ping)
  if (has_ping()) {
    clear_has_test_oneof();
      ::NJoy::Ping* temp = test_oneof_.ping_;
    test_oneof_.ping_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NJoy::Ping& JoyData::ping() const {
  // @@protoc_insertion_point(field_get:NJoy.JoyData.ping)
  return has_ping()
      ? *test_oneof_.ping_
      : *reinterpret_cast< ::NJoy::Ping*>(&::NJoy::_Ping_default_instance_);
}
inline ::NJoy::Ping* JoyData::mutable_ping() {
  if (!has_ping()) {
    clear_test_oneof();
    set_has_ping();
    test_oneof_.ping_ = CreateMaybeMessage< ::NJoy::Ping >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:NJoy.JoyData.ping)
  return test_oneof_.ping_;
}

// optional .NJoy.Axis axis = 3;
inline bool JoyData::has_axis() const {
  return test_oneof_case() == kAxis;
}
inline void JoyData::set_has_axis() {
  _oneof_case_[0] = kAxis;
}
inline void JoyData::clear_axis() {
  if (has_axis()) {
    delete test_oneof_.axis_;
    clear_has_test_oneof();
  }
}
inline ::NJoy::Axis* JoyData::release_axis() {
  // @@protoc_insertion_point(field_release:NJoy.JoyData.axis)
  if (has_axis()) {
    clear_has_test_oneof();
      ::NJoy::Axis* temp = test_oneof_.axis_;
    test_oneof_.axis_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NJoy::Axis& JoyData::axis() const {
  // @@protoc_insertion_point(field_get:NJoy.JoyData.axis)
  return has_axis()
      ? *test_oneof_.axis_
      : *reinterpret_cast< ::NJoy::Axis*>(&::NJoy::_Axis_default_instance_);
}
inline ::NJoy::Axis* JoyData::mutable_axis() {
  if (!has_axis()) {
    clear_test_oneof();
    set_has_axis();
    test_oneof_.axis_ = CreateMaybeMessage< ::NJoy::Axis >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:NJoy.JoyData.axis)
  return test_oneof_.axis_;
}

// optional .NJoy.Button button = 4;
inline bool JoyData::has_button() const {
  return test_oneof_case() == kButton;
}
inline void JoyData::set_has_button() {
  _oneof_case_[0] = kButton;
}
inline void JoyData::clear_button() {
  if (has_button()) {
    delete test_oneof_.button_;
    clear_has_test_oneof();
  }
}
inline ::NJoy::Button* JoyData::release_button() {
  // @@protoc_insertion_point(field_release:NJoy.JoyData.button)
  if (has_button()) {
    clear_has_test_oneof();
      ::NJoy::Button* temp = test_oneof_.button_;
    test_oneof_.button_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NJoy::Button& JoyData::button() const {
  // @@protoc_insertion_point(field_get:NJoy.JoyData.button)
  return has_button()
      ? *test_oneof_.button_
      : *reinterpret_cast< ::NJoy::Button*>(&::NJoy::_Button_default_instance_);
}
inline ::NJoy::Button* JoyData::mutable_button() {
  if (!has_button()) {
    clear_test_oneof();
    set_has_button();
    test_oneof_.button_ = CreateMaybeMessage< ::NJoy::Button >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:NJoy.JoyData.button)
  return test_oneof_.button_;
}

// optional .NJoy.Hat hat = 5;
inline bool JoyData::has_hat() const {
  return test_oneof_case() == kHat;
}
inline void JoyData::set_has_hat() {
  _oneof_case_[0] = kHat;
}
inline void JoyData::clear_hat() {
  if (has_hat()) {
    delete test_oneof_.hat_;
    clear_has_test_oneof();
  }
}
inline ::NJoy::Hat* JoyData::release_hat() {
  // @@protoc_insertion_point(field_release:NJoy.JoyData.hat)
  if (has_hat()) {
    clear_has_test_oneof();
      ::NJoy::Hat* temp = test_oneof_.hat_;
    test_oneof_.hat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NJoy::Hat& JoyData::hat() const {
  // @@protoc_insertion_point(field_get:NJoy.JoyData.hat)
  return has_hat()
      ? *test_oneof_.hat_
      : *reinterpret_cast< ::NJoy::Hat*>(&::NJoy::_Hat_default_instance_);
}
inline ::NJoy::Hat* JoyData::mutable_hat() {
  if (!has_hat()) {
    clear_test_oneof();
    set_has_hat();
    test_oneof_.hat_ = CreateMaybeMessage< ::NJoy::Hat >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:NJoy.JoyData.hat)
  return test_oneof_.hat_;
}

inline bool JoyData::has_test_oneof() const {
  return test_oneof_case() != TEST_ONEOF_NOT_SET;
}
inline void JoyData::clear_has_test_oneof() {
  _oneof_case_[0] = TEST_ONEOF_NOT_SET;
}
inline JoyData::TestOneofCase JoyData::test_oneof_case() const {
  return JoyData::TestOneofCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// JoyListData

// repeated .NJoy.JoyData data = 1;
inline int JoyListData::data_size() const {
  return data_.size();
}
inline void JoyListData::clear_data() {
  data_.Clear();
}
inline ::NJoy::JoyData* JoyListData::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:NJoy.JoyListData.data)
  return data_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::NJoy::JoyData >*
JoyListData::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:NJoy.JoyListData.data)
  return &data_;
}
inline const ::NJoy::JoyData& JoyListData::data(int index) const {
  // @@protoc_insertion_point(field_get:NJoy.JoyListData.data)
  return data_.Get(index);
}
inline ::NJoy::JoyData* JoyListData::add_data() {
  // @@protoc_insertion_point(field_add:NJoy.JoyListData.data)
  return data_.Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::NJoy::JoyData >&
JoyListData::data() const {
  // @@protoc_insertion_point(field_list:NJoy.JoyListData.data)
  return data_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace NJoy

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::NJoy::UpdateType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::NJoy::UpdateType>() {
  return ::NJoy::UpdateType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_protocol_2eproto
